version: 2
updates:
  - package-ecosystem: github-actions # パッケージエコシステム
    directory: /                       # パッケージマニフェストの配置先ディレクトリ
    schedule:
      interval: daily
    ignore:
      - dependency-name: actions/upload-artifact
        versions:
          - 4.3.0
          - 4.3.1
      - dependency-name: 'actions/*'
        updates-types:
          - version-update:semver-major